
all:
	@echo nothing to be done

install:
	install -d $(DESTDIR)/etc/profile.d
	install -d $(DESTDIR)/usr/bin
	install -m755 home-etc.*sh $(DESTDIR)/etc/profile.d
	install -m755 home-etc $(DESTDIR)/usr/bin
