all:
	@echo nothing to be done

install:
	install -d $(DESTDIR)/usr/share/man/man3
	install -d $(DESTDIR)/usr/share/doc/$(NAME)-$(VERSION)
	install -m644 *.txt $(DESTDIR)/usr/share/doc/$(NAME)-$(VERSION)
	install -m644 *.3 $(DESTDIR)/usr/share/man/man3
